/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Clases.ClsCandidato;
import Clases.ClsEleccion;
import Clases.ClsMensaje;
import Controladores.CtlCandidato;
import Controladores.CtlEleccion;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.LinkedList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author davidperezarias
 */
public class FrameElecciones extends javax.swing.JFrame {
    
    CtlCandidato controladorCandidato;
    CtlEleccion controladorEleccion;
    
    LinkedList<ClsEleccion> elecciones;
    FrameMenu menu;

    /**
     * Creates new form FrameElecciones
     */
    public FrameElecciones(FrameMenu menu) {
        initComponents();
        if (menu != null) {
            this.menu = menu;
            this.menu.setVisible(false);
            
        }
        this.elecciones = new LinkedList<>();
        this.controladorCandidato = new CtlCandidato();
        this.controladorEleccion = new CtlEleccion();
        this.ObtenerCandidatos();
        this.ObtenerElecciones();
        this.botonActualizar.setVisible(false);
        this.botonidEleccion.setVisible(false);
    }
    
    public void ObtenerCandidatos() {
        
        LinkedList<ClsCandidato> candidatos = this.controladorCandidato.ObtenerCandidatos();
        
        DefaultComboBoxModel model = (DefaultComboBoxModel) this.comboCandidato.getModel();
        model.removeAllElements();
        
        for (ClsCandidato candidato : candidatos) {
            model.addElement(candidato.getNombre() + "-" + candidato.getNumeroDocumento());
        }

        // setting model with new data
        this.comboCandidato.setModel(model);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelNombre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        comboTipo = new javax.swing.JComboBox<>();
        botonAgregar = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        botonVolver = new javax.swing.JButton();
        campoFechaInicio = new com.toedter.calendar.JDateChooser();
        campoFechaFin = new com.toedter.calendar.JDateChooser();
        botonidEleccion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaElecciones = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCandidatos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonEliminar = new javax.swing.JButton();
        bottonCerrarEleccion = new javax.swing.JButton();
        botonQuitarCandidato = new javax.swing.JButton();
        botonEditar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        comboCandidato = new javax.swing.JComboBox<>();
        botonAsociarCandidato = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        labelNombre.setText("Nombre");

        jLabel3.setText("Tipo");

        jLabel4.setText("Fecha inicio");

        jLabel5.setText("Fecha fin");

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Presidencial", "Municipal" }));

        botonAgregar.setText("Agregar");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        botonActualizar.setText("Actualizar");
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });

        jLabel7.setText("ELECCIONES");

        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(botonActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                        .addGap(395, 395, 395))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNombre))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 115, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(96, 96, 96))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(campoFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(campoFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(125, 125, 125)
                        .addComponent(botonidEleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonVolver)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(botonVolver))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonidEleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)))
                    .addComponent(labelNombre, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoFechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(campoFechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAgregar)
                    .addComponent(botonActualizar))
                .addGap(23, 23, 23))
        );

        tablaElecciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Eleccion", "Fecha inicio", "Fecha fin", "Estado", "Ganador"
            }
        ));
        tablaElecciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEleccionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaElecciones);

        tablaCandidatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id", "Candidato"
            }
        ));
        jScrollPane2.setViewportView(tablaCandidatos);

        jLabel1.setText("Listado elecciones");

        jLabel2.setText("Listado candidatos por elección");

        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        bottonCerrarEleccion.setText("Cerrar");
        bottonCerrarEleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonCerrarEleccionActionPerformed(evt);
            }
        });

        botonQuitarCandidato.setText("Eliminar");
        botonQuitarCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonQuitarCandidatoActionPerformed(evt);
            }
        });

        botonEditar.setText("Editar");
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Candidato");

        comboCandidato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        botonAsociarCandidato.setText("Asociar");
        botonAsociarCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAsociarCandidatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAsociarCandidato)
                    .addComponent(jLabel6)
                    .addComponent(comboCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonAsociarCandidato)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 487, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bottonCerrarEleccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)))
                            .addComponent(botonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonQuitarCandidato))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(bottonCerrarEleccion)
                        .addGap(18, 18, 18)
                        .addComponent(botonEditar)))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(botonQuitarCandidato))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        
        String nombre = this.campoNombre.getText();
        String tipo = this.comboTipo.getSelectedItem().toString();
        
        SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
        
        String fechaInicio = formatoFecha.format(this.campoFechaInicio.getDate());
        String fechaFin = formatoFecha.format(this.campoFechaFin.getDate());
        String[] partesFecha = fechaInicio.split("-", 2);
        int idEleccion = Integer.parseInt(partesFecha[0]);
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDate fecha1 = LocalDate.parse(fechaInicio, formato);
        LocalDate fecha2 = LocalDate.parse(fechaFin, formato);
        
        if (!fecha1.isAfter(fecha2)) {
            ClsEleccion eleccion = new ClsEleccion(idEleccion, nombre, tipo, fechaInicio, fechaFin, "creado", null);
            
            ClsMensaje respuesta = this.controladorEleccion.AgregarEleccion(eleccion);
            
            if (respuesta.getTipo().equals(ClsMensaje.OK)) {
                this.ObtenerElecciones();
                ReiniciarFormulario();
            }
            JOptionPane.showMessageDialog(rootPane, respuesta.getDescripcion());
        } else if (!fecha1.isBefore(fecha2)) {
            ClsMensaje mensaje = new ClsMensaje();
            mensaje.CambiarMensaje(mensaje.ERROR, "verifique orden de las fechas");
            JOptionPane.showMessageDialog(rootPane, mensaje.getDescripcion());
        }
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        
        int column = 0;
        int row = this.tablaElecciones.getSelectedRow();
        String idEleccion = this.tablaElecciones.getModel().getValueAt(row, column).toString();
        ClsMensaje mensaje = this.controladorEleccion.EliminarEleccion(idEleccion);
        if (mensaje.getTipo().equals(mensaje.OK)) {
            this.ObtenerElecciones();
        }
        JOptionPane.showMessageDialog(rootPane, mensaje.getDescripcion());
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonAsociarCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAsociarCandidatoActionPerformed
        
        try {
            int column = 0;
            int row = this.tablaElecciones.getSelectedRow();
            String idEleccion = this.tablaElecciones.getModel().getValueAt(row, column).toString();
            
            String[] partesComboCandidato = this.comboCandidato.getSelectedItem().toString().split("-", 2);
            
            String idCandidato = partesComboCandidato[1];
            
            ClsMensaje mensaje = this.controladorEleccion.AsociarCandidato(idEleccion, idCandidato);
            
            if (mensaje.getTipo().equals(mensaje.OK)) {
                
                LinkedList<ClsCandidato> lista = this.controladorEleccion.ObtenerCandidatosEleccion(idEleccion);
                
                this.ActualizarTablaCandidatosEleccion(lista);
            }
            
            JOptionPane.showMessageDialog(rootPane, mensaje.getDescripcion());
        } catch (ArrayIndexOutOfBoundsException e) {
            
            JOptionPane.showMessageDialog(rootPane, "Debes seleccionar una elección");
        }
        

    }//GEN-LAST:event_botonAsociarCandidatoActionPerformed

    private void tablaEleccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEleccionesMouseClicked
        
        int column = 0;
        int row = this.tablaElecciones.getSelectedRow();
        String idEleccion = this.tablaElecciones.getModel().getValueAt(row, column).toString();
        LinkedList<ClsCandidato> lista = this.controladorEleccion.ObtenerCandidatosEleccion(idEleccion);
        
        this.ActualizarTablaCandidatosEleccion(lista);

    }//GEN-LAST:event_tablaEleccionesMouseClicked

    private void botonQuitarCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonQuitarCandidatoActionPerformed
        try {
            int columnE = 0;
            int rowE = this.tablaElecciones.getSelectedRow();
            int columnC = 0;
            int rowC = this.tablaCandidatos.getSelectedRow();
            String idElec = this.tablaElecciones.getModel().getValueAt(rowE, columnE).toString();
            String idCandidato = this.tablaCandidatos.getModel().getValueAt(rowC, columnC).toString();
            ClsMensaje mensaje = this.controladorEleccion.EliminarCandidatoEleccion(idElec, idCandidato);
            
            if (mensaje.getTipo().equals(mensaje.OK)) {
                LinkedList<ClsCandidato> lista = this.controladorEleccion.ObtenerCandidatosEleccion(idElec);
                
                this.ActualizarTablaCandidatosEleccion(lista);
            }
            
            JOptionPane.showMessageDialog(rootPane, mensaje.getDescripcion());
        } catch (ArrayIndexOutOfBoundsException e) {
            
            JOptionPane.showMessageDialog(rootPane, "Debes seleccionar un candidato");
        }
    }//GEN-LAST:event_botonQuitarCandidatoActionPerformed

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
        
        int column = 0;
        int row = this.tablaElecciones.getSelectedRow();
        int id = Integer.parseInt(this.tablaElecciones.getModel().getValueAt(row, column).toString());
        ClsEleccion eleccion = this.BuscarEleccion(id);
        
        if (eleccion != null) {
            this.campoNombre.setText(eleccion.getNombre());
            this.comboTipo.setSelectedItem(eleccion.getTipo());
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            java.sql.Date fechaConvertida = null;
            java.sql.Date fechaConvertida2 = null;
            try {
                Date parsed = dateFormat.parse(eleccion.getFechaInicio());
                Date parsed2 = dateFormat.parse(eleccion.getFechaFin());
                fechaConvertida = new java.sql.Date(parsed.getTime());
                fechaConvertida2 = new java.sql.Date(parsed2.getTime());
            } catch (Exception e) {
                System.out.println("Error occurred" + e.getMessage());
            }
            this.campoFechaInicio.setDate(fechaConvertida);
            this.campoFechaFin.setDate(fechaConvertida2);
            this.botonidEleccion.setText(String.valueOf(id));

//            this.botonNuevo.setVisible(true);
            this.botonActualizar.setVisible(true);
            //        this.botonAgregar.setVisible(false);

            //      this.jTabbedPane1.setSelectedIndex(0);
        }
    }//GEN-LAST:event_botonEditarActionPerformed

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
        int id = Integer.parseInt(this.botonidEleccion.getText());
        ClsEleccion eleccion = this.BuscarEleccion(id);
        String nombre = this.campoNombre.getText();
        eleccion.setNombre(nombre);
        String tipo = this.comboTipo.getSelectedItem().toString();
        eleccion.setTipo(tipo);
        SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
        
        String fechaInicio = formatoFecha.format(this.campoFechaInicio.getDate());
        String fechaFin = formatoFecha.format(this.campoFechaFin.getDate());
        String[] partesFecha = fechaInicio.split("-", 2);
        int idEleccion = Integer.parseInt(partesFecha[0]);
        eleccion.setFechaInicio(fechaInicio);
        eleccion.setFechaFin(fechaFin);
        eleccion.setIdEleccion(idEleccion);
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDate fecha1 = LocalDate.parse(fechaInicio, formato);
        LocalDate fecha2 = LocalDate.parse(fechaFin, formato);
        
        if (!fecha1.isAfter(fecha2)) {
            ClsMensaje mensaje = this.controladorEleccion.ActualizarElecion(eleccion, id);
            
            if (mensaje.getTipo().equals(mensaje.OK)) {
                this.ObtenerElecciones();
                botonidEleccion.setText(String.valueOf(eleccion.getIdEleccion()));
                ReiniciarFormulario();
                this.botonActualizar.setVisible(false);
                
            }
            
            JOptionPane.showMessageDialog(rootPane, mensaje.getDescripcion());
        } else if (!fecha1.isBefore(fecha2)) {
            ClsMensaje mensaje = new ClsMensaje();
            mensaje.CambiarMensaje(mensaje.ERROR, "verifique orden de las fechas");
            JOptionPane.showMessageDialog(rootPane, mensaje.getDescripcion());
        }
    }//GEN-LAST:event_botonActualizarActionPerformed
    

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        this.setVisible(false);
        menu.setVisible(true);

    }//GEN-LAST:event_botonVolverActionPerformed

    private void bottonCerrarEleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonCerrarEleccionActionPerformed
       try {
        int column = 0;
        int row = this.tablaElecciones.getSelectedRow();
        int id = Integer.parseInt(this.tablaElecciones.getModel().getValueAt(row, column).toString());
        ClsEleccion eleccion = this.BuscarEleccion(id);
        String ganador = this.controladorEleccion.ObtenerGanador(2022);
        System.out.println(ganador);
        eleccion.setEstado("cerrada");
        eleccion.setGanador(ganador);
        ClsMensaje mensaje = this.controladorEleccion.ActualizarElecion(eleccion, id);
            
            if (mensaje.getTipo().equals(mensaje.OK)) {
                this.ObtenerElecciones();
                botonidEleccion.setText(String.valueOf(eleccion.getIdEleccion()));

            }
            
            JOptionPane.showMessageDialog(rootPane, mensaje.getDescripcion());
       }catch (ArrayIndexOutOfBoundsException e) {
            
            JOptionPane.showMessageDialog(rootPane, "Debes seleccionar una elección");
        }
    }//GEN-LAST:event_bottonCerrarEleccionActionPerformed
    
    public void ObtenerElecciones() {
        
        this.elecciones = this.controladorEleccion.ObtenerElecciones();
        this.ActualizarTabla(this.elecciones);
        
    }
    
    public ClsEleccion BuscarEleccion(int id) {
        
        for (ClsEleccion eleccion : this.elecciones) {
            
            if (eleccion.getIdEleccion() == id) {
                return eleccion;
            }
            
        }
        
        return null;
        
    }
    
    public void ReiniciarFormulario() {
        this.campoNombre.setText("");
    }
    
    public static Date getDateFormat(String formatPattern, String date) throws ParseException {
        SimpleDateFormat formatter = new SimpleDateFormat(formatPattern);
        return formatter.parse(date);
    }
    
    public void ActualizarTabla(LinkedList<ClsEleccion> lista) {
        
        DefaultTableModel model = (DefaultTableModel) this.tablaElecciones.getModel();
        
        model.setRowCount(0);
        
        for (ClsEleccion eleccion : lista) {
            
            Object[] row = {
                eleccion.getIdEleccion(),
                eleccion.getNombre(),
                eleccion.getFechaInicio(),
                eleccion.getFechaFin(),
                eleccion.getEstado(),
                eleccion.getGanador()
            };
            model.addRow(row);
            
        }
        
    }
    
    public void ActualizarTablaCandidatosEleccion(LinkedList<ClsCandidato> lista) {
        
        DefaultTableModel model = (DefaultTableModel) this.tablaCandidatos.getModel();
        
        model.setRowCount(0);
        
        for (ClsCandidato candidato : lista) {
            
            Object[] row = {
                candidato.getNumeroDocumento(),
                candidato.getNombre(),
                "",
                ""
            };
            model.addRow(row);
            
        }
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameElecciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameElecciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameElecciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameElecciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameElecciones(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonAsociarCandidato;
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonQuitarCandidato;
    private javax.swing.JButton botonVolver;
    private javax.swing.JTextField botonidEleccion;
    private javax.swing.JButton bottonCerrarEleccion;
    private com.toedter.calendar.JDateChooser campoFechaFin;
    private com.toedter.calendar.JDateChooser campoFechaInicio;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JComboBox<String> comboCandidato;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JTable tablaCandidatos;
    private javax.swing.JTable tablaElecciones;
    // End of variables declaration//GEN-END:variables
}
