/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Clases.ClsEleccion;
import Controladores.CtlEleccion;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import java.util.LinkedList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author davidperezarias
 */
public class FrameMenu extends javax.swing.JFrame {

    LinkedList<ClsEleccion> elecciones;
    CtlEleccion controladorEleccion;

    /**
     * Creates new form FrameMenu
     */
    public FrameMenu() {
        initComponents();

        this.elecciones = new LinkedList<>();
        this.controladorEleccion = new CtlEleccion();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botonCandidatos = new javax.swing.JButton();
        botonVotante = new javax.swing.JButton();
        botonVotar = new javax.swing.JButton();
        botonGestionElecciones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("InaiMathi", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 135, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Elecciones");

        botonCandidatos.setText("Gestionar candidato");
        botonCandidatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCandidatosActionPerformed(evt);
            }
        });

        botonVotante.setText("Registro de votante");
        botonVotante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVotanteActionPerformed(evt);
            }
        });

        botonVotar.setText("Votar");
        botonVotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVotarActionPerformed(evt);
            }
        });

        botonGestionElecciones.setText("Gestionar elecciones");
        botonGestionElecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGestionEleccionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonCandidatos)
                            .addComponent(botonGestionElecciones))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonVotar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonVotante))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonVotante, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(botonCandidatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonVotar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonGestionElecciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCandidatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCandidatosActionPerformed
        FrameGestorCandidato gestioncandidato = new FrameGestorCandidato(this);
        gestioncandidato.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_botonCandidatosActionPerformed

    private void botonVotanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVotanteActionPerformed
        FrameGestorVotante gestionvotante = new FrameGestorVotante(this);
        this.setVisible(false);
        gestionvotante.setVisible(true);
    }//GEN-LAST:event_botonVotanteActionPerformed

    private void botonGestionEleccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGestionEleccionesActionPerformed
        FrameElecciones gestioneleccion = new FrameElecciones(this);
        this.setVisible(false);
        gestioneleccion.setVisible(true);
    }//GEN-LAST:event_botonGestionEleccionesActionPerformed

    private void botonVotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVotarActionPerformed
        SimpleDateFormat dtf = new SimpleDateFormat("yyyy-MM-dd");
        Calendar calendar = Calendar.getInstance();

        Date dateObj = calendar.getTime();
        String formattedDate = dtf.format(dateObj);
        String[] partesFecha = formattedDate.split("-", 2);
        int fechaHoy = Integer.parseInt(partesFecha[0]);
        ClsEleccion eleccion = this.BuscarEleccion(fechaHoy);
        if (eleccion != null) {
            if (!eleccion.getEstado().equals("cerrada")) {
                DateTimeFormatter formato = DateTimeFormatter.ofPattern("yyyy-MM-dd");
                LocalDate fecha1 = LocalDate.parse(formattedDate, formato);
                LocalDate fecha2 = LocalDate.parse(eleccion.getFechaInicio(), formato);
                LocalDate fecha3 = LocalDate.parse(eleccion.getFechaFin(), formato);
                if (!fecha2.isAfter(fecha1)) {
                    if (!fecha1.isAfter(fecha3)) {
                        this.setVisible(false);
                        FrameVotar gestionvotar = new FrameVotar(this, fechaHoy);
                        gestionvotar.setVisible(true);
                        this.setVisible(false);

                    } else {
                         JOptionPane.showMessageDialog(rootPane, "la eleccion ya finalizo");
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "la eleccion no ha iniciado");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "no hay elecciones abiertas");
            }
            
                    
        }else{
        JOptionPane.showMessageDialog(rootPane, "la eleccion ya finalizo");
        }
    }//GEN-LAST:event_botonVotarActionPerformed

    

    public ClsEleccion BuscarEleccion(int id) {
        ObtenerElecciones();
        for (ClsEleccion eleccion : this.elecciones) {
            if (eleccion.getIdEleccion() == id) {
                return eleccion;
            }
        }
        return null;
    }

    public void ObtenerElecciones() {
        this.elecciones = this.controladorEleccion.ObtenerElecciones();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCandidatos;
    private javax.swing.JButton botonGestionElecciones;
    private javax.swing.JButton botonVotante;
    private javax.swing.JButton botonVotar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
