/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Clases.ClsCandidato;
import Clases.ClsMensaje;
import Clases.ClsPropuesta;
import Controladores.CtlCandidato;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author davidperezarias
 */
public class FrameGestorCandidato extends javax.swing.JFrame {
    
    CtlCandidato controlador;
    LinkedList<ClsCandidato> candidatos;
    LinkedList<ClsPropuesta> propuestas;
    FrameMenu menu;

    /**
     * Creates new form FrameGestorCandidato
     */
    public FrameGestorCandidato(FrameMenu menu) {
        initComponents();
        if (menu != null) {
            this.menu = menu;
            this.menu.setVisible(false);
            
        }
        this.botonNuevo.setVisible(false);
        this.botonActualizar.setVisible(false);
        this.botonActualizarPropuesta.setVisible(false);
        this.botonNuevoPropuesta.setVisible(false);
        this.campoIdPropuesta.setVisible(false);
        this.controlador = new CtlCandidato();
        this.ObtenerCandidatos();
    }
    
    public void ObtenerCandidatos() {
        
        this.candidatos = this.controlador.ObtenerCandidatos();
        this.ActualizarTabla(candidatos);
        
    }
    
    public void ActualizarTabla(LinkedList<ClsCandidato> lista) {
        
        DefaultTableModel model = (DefaultTableModel) this.tablaCandidatos.getModel();
        
        model.setRowCount(0);
        
        for (ClsCandidato candidato : lista) {
            
            Object[] row = {candidato.getNumeroDocumento(), candidato.getNombre(), candidato.getPartidoPolitico(), candidato.getDescripcion()};
            model.addRow(row);
            
        }
        
    }
    
    public void ActualizarTablaPropuestas(LinkedList<ClsPropuesta> lista) {
        
        DefaultTableModel model = (DefaultTableModel) this.tablaPropuestas.getModel();
        
        model.setRowCount(0);
        
        for (ClsPropuesta propuesta : lista) {
            
            Object[] row = {propuesta.getIdPropuesta(), propuesta.getSector(),
                propuesta.getDescripcion()};
            model.addRow(row);
            
        }
        
    }
    
    public ClsCandidato BuscarCandidato(String id) {
        
        for (ClsCandidato candidato : this.candidatos) {
            
            if (candidato.getNumeroDocumento().equals(id)) {
                return candidato;
            }
            
        }
        
        return null;
        
    }
    
    public ClsPropuesta BuscarPropuesta(String id) {
        
        for (ClsPropuesta propuesta : this.propuestas) {
            
            if (propuesta.getIdPropuesta().equals(id)) {
                return propuesta;
            }
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        campoNumeroCedula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoTelefono = new javax.swing.JTextField();
        campoCorreo = new javax.swing.JTextField();
        comboPartido = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        botonAgregar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoDescripcion = new javax.swing.JTextArea();
        botonActualizar = new javax.swing.JButton();
        botonNuevo = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        comboCiudad = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        campoMensaje = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCandidatos = new javax.swing.JTable();
        botonEliminar = new javax.swing.JButton();
        botonIrEditar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        labelSector = new javax.swing.JLabel();
        comboSector = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        campoDescripcionPropuesta = new javax.swing.JTextArea();
        botonAgregarPropuesta = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane6 = new javax.swing.JScrollPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaPropuestas = new javax.swing.JTable();
        botonEliminarPropuesta = new javax.swing.JButton();
        botonEditarPropuesta = new javax.swing.JButton();
        botonActualizarPropuesta = new javax.swing.JButton();
        CandidatoPropuesta = new javax.swing.JLabel();
        campoIdPropuesta = new javax.swing.JTextField();
        labelSector1 = new javax.swing.JLabel();
        botonNuevoPropuesta = new javax.swing.JButton();
        botonMenu = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Gestión de candidato");

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jLabel2.setText("Número cédula");

        jLabel3.setText("Nombre");

        jLabel4.setText("Telefono");

        jLabel5.setText("Correo");

        comboPartido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Democrata", "Verde", "Pacto histórico", "Liberal" }));

        jLabel6.setText("Partido");

        botonAgregar.setText("Agregar");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        jLabel7.setText("Descripción");

        campoDescripcion.setColumns(20);
        campoDescripcion.setRows(5);
        jScrollPane2.setViewportView(campoDescripcion);

        botonActualizar.setText("Actualizar");
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });

        botonNuevo.setText("Nuevo");
        botonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoActionPerformed(evt);
            }
        });

        jLabel9.setText("Ciudad de Origen");

        comboCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arauca", "Bucaramanga", "Bogota", "Cartagena", "Choco" }));
        comboCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCiudadActionPerformed(evt);
            }
        });

        jLabel10.setText("Mensaje Campaña");

        campoMensaje.setColumns(20);
        campoMensaje.setRows(5);
        jScrollPane7.setViewportView(campoMensaje);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoNumeroCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addComponent(comboPartido, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(comboCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(campoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(botonActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonNuevo))
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNumeroCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboPartido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(comboCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAgregar)
                    .addComponent(botonActualizar)
                    .addComponent(botonNuevo))
                .addGap(16, 16, 16))
        );

        jTabbedPane1.addTab("Formulario", jPanel1);

        tablaCandidatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Candidato", "Partido", "Descripción"
            }
        ));
        jScrollPane1.setViewportView(tablaCandidatos);

        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        botonIrEditar.setText("Ir al editar");
        botonIrEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIrEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonIrEditar)
                .addGap(63, 63, 63)
                .addComponent(botonEliminar)
                .addGap(112, 112, 112))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEliminar)
                    .addComponent(botonIrEditar))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lista", jPanel2);

        labelSector.setText("Sector");

        comboSector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Salud", "Seguridad", "Agrícultura", "TI", "Hacienda" }));

        jLabel8.setText("Propuesta");

        campoDescripcionPropuesta.setColumns(20);
        campoDescripcionPropuesta.setRows(5);
        jScrollPane3.setViewportView(campoDescripcionPropuesta);

        botonAgregarPropuesta.setText("Agregar");
        botonAgregarPropuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarPropuestaActionPerformed(evt);
            }
        });

        tablaPropuestas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Sector", "Propuesta"
            }
        ));
        jScrollPane5.setViewportView(tablaPropuestas);

        jScrollPane6.setViewportView(jScrollPane5);

        botonEliminarPropuesta.setText("Eliminar");
        botonEliminarPropuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarPropuestaActionPerformed(evt);
            }
        });

        botonEditarPropuesta.setText("Editar");
        botonEditarPropuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarPropuestaActionPerformed(evt);
            }
        });

        botonActualizarPropuesta.setText("Guardar");
        botonActualizarPropuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarPropuestaActionPerformed(evt);
            }
        });

        CandidatoPropuesta.setText("Sin cadidato");

        botonNuevoPropuesta.setText("Nuevo");
        botonNuevoPropuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoPropuestaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonEliminarPropuesta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonEditarPropuesta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelSector)
                                    .addComponent(comboSector, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(labelSector1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoIdPropuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 7, Short.MAX_VALUE))
                            .addComponent(jSeparator1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonAgregarPropuesta)
                            .addComponent(botonNuevoPropuesta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(botonActualizarPropuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(6, 6, 6))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(CandidatoPropuesta)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(CandidatoPropuesta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSector)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(comboSector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoIdPropuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelSector1))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(botonAgregarPropuesta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonActualizarPropuesta)
                        .addGap(12, 12, 12)
                        .addComponent(botonNuevoPropuesta)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(botonEliminarPropuesta)
                        .addGap(18, 18, 18)
                        .addComponent(botonEditarPropuesta)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Propuestas", jPanel3);

        botonMenu.setText("Menu principal");
        botonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(330, 330, 330))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonMenu)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonMenu)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        
        String numeroCedula = campoNumeroCedula.getText();
        String nombre = campoNombre.getText();
        String telefono = campoTelefono.getText();
        String correo = campoCorreo.getText();
        String partido = comboPartido.getSelectedItem().toString();
        String ciudad = comboCiudad.getSelectedItem().toString();
        String descripcion = campoDescripcion.getText();
        String mensajeCampania = campoMensaje.getText();
        ClsCandidato candidato = new ClsCandidato(partido, ciudad, descripcion, mensajeCampania, numeroCedula, nombre, telefono, correo);
        
        ClsMensaje mensaje = this.controlador.AgregarCandidato(candidato);
        
        if (mensaje.getTipo().equals(mensaje.OK)) {
            this.ObtenerCandidatos();
            ReiniciarFormulario();
        }
        
        JOptionPane.showMessageDialog(rootPane, mensaje.getDescripcion());

    }//GEN-LAST:event_botonAgregarActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        int column = 0;
        int row = this.tablaCandidatos.getSelectedRow();
        String cedula = this.tablaCandidatos.getModel().getValueAt(row, column).toString();
        
        ClsMensaje mensaje = this.controlador.EliminarCandidato(cedula);
        
        if (mensaje.getTipo().equals(mensaje.OK)) {
            this.ObtenerCandidatos();
        }
        
        JOptionPane.showMessageDialog(rootPane, mensaje.getDescripcion());
        

    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonIrEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIrEditarActionPerformed
        int column = 0;
        int row = this.tablaCandidatos.getSelectedRow();
        String cedula = this.tablaCandidatos.getModel().getValueAt(row, column).toString();
        ClsCandidato candidato = this.BuscarCandidato(cedula);
        
        if (candidato != null) {
            this.campoNumeroCedula.setText(candidato.getNumeroDocumento());
            this.campoNombre.setText(candidato.getNombre());
            this.campoTelefono.setText(candidato.getTelefono());
            this.campoCorreo.setText(candidato.getCorreo());
            this.campoDescripcion.setText(candidato.getDescripcion());
            this.comboPartido.setSelectedItem(candidato.getPartidoPolitico());
            this.comboCiudad.setSelectedItem(candidato.getCiudadorigen());
            this.campoMensaje.setText(candidato.getMensajeCampania());
            
            this.campoNumeroCedula.disable();
            
            this.botonNuevo.setVisible(true);
            this.botonActualizar.setVisible(true);
            this.botonAgregar.setVisible(false);
            
            this.jTabbedPane1.setSelectedIndex(0);
        }
        

    }//GEN-LAST:event_botonIrEditarActionPerformed

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
        
        String cedula = this.campoNumeroCedula.getText();
        ClsCandidato candidato = this.BuscarCandidato(cedula);
        
        String nombre = this.campoNombre.getText();
        candidato.setNombre(nombre);
        
        String descri = this.campoDescripcion.getText();
        candidato.setDescripcion(descri);
        
        String telefono = this.campoTelefono.getText();
        candidato.setTelefono(telefono);
        
        String correo = this.campoCorreo.getText();
        candidato.setCorreo(correo);
        
        String partido = this.comboPartido.getSelectedItem().toString();
        candidato.setPartidoPolitico(partido);
        
        String ciudad = this.comboCiudad.getSelectedItem().toString();
        candidato.setCiudadorigen(ciudad);
        
        String mensajec = this.campoMensaje.getText();
        candidato.setMensajeCampania(mensajec);
        
        ClsMensaje mensaje = this.controlador.ActualizarCandidato(candidato);
        
        if (mensaje.getTipo().equals(mensaje.OK)) {
            this.ObtenerCandidatos();
            
        }
        
        JOptionPane.showMessageDialog(rootPane, mensaje.getDescripcion());
        

    }//GEN-LAST:event_botonActualizarActionPerformed

    private void botonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoActionPerformed
        
        this.botonNuevo.setVisible(false);
        this.botonActualizar.setVisible(false);
        this.botonAgregar.setVisible(true);
        this.campoNumeroCedula.enable();
        
        ReiniciarFormulario();
    }//GEN-LAST:event_botonNuevoActionPerformed

    private void botonAgregarPropuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarPropuestaActionPerformed
        
        String sector = this.comboSector.getSelectedItem().toString();
        String descripcion = this.campoDescripcionPropuesta.getText();
        
        int column = 0;
        int row = this.tablaCandidatos.getSelectedRow();
        String cedula = this.tablaCandidatos.getModel().getValueAt(row, column).toString();
        ClsCandidato candidato = this.BuscarCandidato(cedula);
        
        if (candidato != null) {
            ClsPropuesta propuesta = new ClsPropuesta(cedula, sector, descripcion);
            
            ClsMensaje respuesta = this.controlador.AgregarPropuesta(propuesta);
            
            if (respuesta.getTipo().equals(ClsMensaje.OK)) {
                propuesta.setIdPropuesta(respuesta.getData());
                candidato.getPropuestas().add(propuesta);
                this.ActualizarTablaPropuestas(candidato.getPropuestas());
                this.campoDescripcionPropuesta.setText("");
            }
            
        }
        

    }//GEN-LAST:event_botonAgregarPropuestaActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        
        int index = this.jTabbedPane1.getSelectedIndex();
        if (index == 2) {
            
            int column = 0;
            int row = this.tablaCandidatos.getSelectedRow();
            String idCandidato = this.tablaCandidatos.getModel().getValueAt(row, column).toString();
            
            ClsCandidato candidato = this.BuscarCandidato(idCandidato);
            
            if (candidato != null) {
                
                propuestas = this.controlador.ObtenerPropuestas(idCandidato);
                CandidatoPropuesta.setText(candidato.getNombre());
                if (propuestas != null) {
                    candidato.setPropuestas(propuestas);
                    this.ActualizarTablaPropuestas(candidato.getPropuestas());
                }
                
            }
        }
        

    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void comboCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCiudadActionPerformed

    }//GEN-LAST:event_comboCiudadActionPerformed

    private void botonEditarPropuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarPropuestaActionPerformed
        int column = 0;
        int row = this.tablaPropuestas.getSelectedRow();
        String id = this.tablaPropuestas.getModel().getValueAt(row, column).toString();
        ClsPropuesta propuesta = this.BuscarPropuesta(id);
        
        if (propuesta != null) {
            this.campoIdPropuesta.setText(propuesta.getIdPropuesta());
            this.campoDescripcionPropuesta.setText(propuesta.getDescripcion());
            this.comboSector.setSelectedItem(propuesta.getSector());
            this.botonActualizarPropuesta.setVisible(true);
            this.botonNuevoPropuesta.setVisible(true);
            this.botonAgregarPropuesta.setVisible(false);
        }
    }//GEN-LAST:event_botonEditarPropuestaActionPerformed

    private void botonActualizarPropuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarPropuestaActionPerformed
        
        String id = this.campoIdPropuesta.getText();
        ClsPropuesta propuesta = this.BuscarPropuesta(id);
        
        String sector = this.comboSector.getSelectedItem().toString();
        propuesta.setSector(sector);
        
        String descripcion = this.campoDescripcionPropuesta.getText();
        propuesta.setDescripcion(descripcion);
        
        ClsMensaje mensaje = this.controlador.ActualizarPropuesta(propuesta);
        
        if (mensaje.getTipo().equals(mensaje.OK)) {
            int col = 0;
            int ro = this.tablaCandidatos.getSelectedRow();
            String cedula = this.tablaCandidatos.getModel().getValueAt(ro, col).toString();
            ClsCandidato candidato = this.BuscarCandidato(cedula);
            propuestas = this.controlador.ObtenerPropuestas(cedula);
            if (propuestas != null) {
                candidato.setPropuestas(propuestas);
                this.ActualizarTablaPropuestas(candidato.getPropuestas());
                this.campoDescripcionPropuesta.setText("");
                this.botonActualizarPropuesta.setVisible(false);
                this.botonNuevoPropuesta.setVisible(false);
                this.botonAgregarPropuesta.setVisible(true);
            }
        }
        JOptionPane.showMessageDialog(rootPane, mensaje.getDescripcion());
    }//GEN-LAST:event_botonActualizarPropuestaActionPerformed

    private void botonEliminarPropuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarPropuestaActionPerformed
        int column = 0;
        int row = this.tablaPropuestas.getSelectedRow();
        String id = this.tablaPropuestas.getModel().getValueAt(row, column).toString();
        ClsMensaje mensaje = this.controlador.EliminarPropuestas(id);
        
        if (mensaje.getTipo().equals(mensaje.OK)) {
            int col = 0;
            int ro = this.tablaCandidatos.getSelectedRow();
            String cedula = this.tablaCandidatos.getModel().getValueAt(ro, col).toString();
            ClsCandidato candidato = this.BuscarCandidato(cedula);
            propuestas = this.controlador.ObtenerPropuestas(cedula);
            if (propuestas != null) {
                candidato.setPropuestas(propuestas);
                this.ActualizarTablaPropuestas(candidato.getPropuestas());
            }
        }
        
        JOptionPane.showMessageDialog(rootPane, mensaje.getDescripcion());
    }//GEN-LAST:event_botonEliminarPropuestaActionPerformed

    private void botonNuevoPropuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoPropuestaActionPerformed
        this.botonActualizarPropuesta.setVisible(false);
        this.botonNuevoPropuesta.setVisible(false);
        this.botonAgregarPropuesta.setVisible(true);
        this.campoDescripcionPropuesta.setText("");
    }//GEN-LAST:event_botonNuevoPropuestaActionPerformed

    private void botonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenuActionPerformed
        this.setVisible(false);
        menu.setVisible(true);
        
    }//GEN-LAST:event_botonMenuActionPerformed
    public void ReiniciarFormulario() {
        this.campoNumeroCedula.setText("");
        this.campoNombre.setText("");
        this.campoTelefono.setText("");
        this.campoCorreo.setText("");
        this.campoDescripcion.setText("");
        this.campoMensaje.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameGestorCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameGestorCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameGestorCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameGestorCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameGestorCandidato(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CandidatoPropuesta;
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonActualizarPropuesta;
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonAgregarPropuesta;
    private javax.swing.JButton botonEditarPropuesta;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonEliminarPropuesta;
    private javax.swing.JButton botonIrEditar;
    private javax.swing.JButton botonMenu;
    private javax.swing.JButton botonNuevo;
    private javax.swing.JButton botonNuevoPropuesta;
    private javax.swing.JTextField campoCorreo;
    private javax.swing.JTextArea campoDescripcion;
    private javax.swing.JTextArea campoDescripcionPropuesta;
    private javax.swing.JTextField campoIdPropuesta;
    private javax.swing.JTextArea campoMensaje;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoNumeroCedula;
    private javax.swing.JTextField campoTelefono;
    private javax.swing.JComboBox<String> comboCiudad;
    private javax.swing.JComboBox<String> comboPartido;
    private javax.swing.JComboBox<String> comboSector;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelSector;
    private javax.swing.JLabel labelSector1;
    private javax.swing.JTable tablaCandidatos;
    private javax.swing.JTable tablaPropuestas;
    // End of variables declaration//GEN-END:variables
}
