/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Clases.ClsCandidato;
import Clases.ClsVotante;
import Controladores.CtlEleccion;
import Controladores.CtlVotante;
import java.util.LinkedList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import Clases.ClsVoto;
import Controladores.CtlVotar;
import Clases.ClsMensaje;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class FrameVotar extends javax.swing.JFrame {

    CtlVotar controladorVoto;
    CtlVotante controlador;
    LinkedList<ClsVotante> Votantes;
    LinkedList<ClsVoto> Votos;
    FrameMenu menu;
    CtlEleccion controladorEleccion;

    /**
     * Creates new form FrameVotar
     */
    public FrameVotar(FrameMenu menu, int idEleccion) {
        initComponents();
        if (menu != null && idEleccion != 0) {
            this.menu = menu;
            this.menu.setVisible(false);
            comboCandidatos.setVisible(false);
            botonVotar.setVisible(false);

        }
        labelId.setText(Integer.toString(idEleccion));
        this.controlador = new CtlVotante();
        this.controladorEleccion = new CtlEleccion();
        this.controladorVoto = new CtlVotar();
        labelVotante.setVisible(false);
        labelCandidato.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelId = new javax.swing.JLabel();
        campoCedula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        botonVerificar = new javax.swing.JButton();
        botonMenu = new javax.swing.JButton();
        comboCandidatos = new javax.swing.JComboBox<>();
        botonVotar = new javax.swing.JButton();
        labelVotante = new javax.swing.JLabel();
        labelCandidato = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bienvenido a las elecciones:");

        labelId.setText("jLabel2");

        campoCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCedulaActionPerformed(evt);
            }
        });

        jLabel2.setText("Digite su documento");

        botonVerificar.setText("verificar");
        botonVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerificarActionPerformed(evt);
            }
        });

        botonMenu.setText("Menu principal");
        botonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenuActionPerformed(evt);
            }
        });

        comboCandidatos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        botonVotar.setText("Votar");
        botonVotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVotarActionPerformed(evt);
            }
        });

        labelVotante.setText("jLabel3");

        labelCandidato.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelVotante)
                    .addComponent(labelCandidato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(115, 115, 115))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(labelId)
                                .addGap(176, 176, 176)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(151, 151, 151)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonMenu)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(campoCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonVerificar)))
                        .addGap(19, 19, 19))))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(comboCandidatos, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(botonVotar)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelVotante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelId)
                    .addComponent(labelCandidato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonVerificar))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCandidatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonVotar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(botonMenu)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCedulaActionPerformed

    }//GEN-LAST:event_campoCedulaActionPerformed

    private void botonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenuActionPerformed
        this.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_botonMenuActionPerformed

    private void botonVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerificarActionPerformed
        String cedula = campoCedula.getText();
        ObtenerVotantes();
        ClsVotante votante = this.BuscarVotante(cedula);
        ObtenerVotos();
        ClsVoto voto = this.BuscarVoto(Integer.parseInt(labelId.getText()),cedula);
        if (voto == null) {
            if (votante != null) {
                ObtenerCandidatos(labelId.getText());
                labelVotante.setText(votante.getNumeroDocumento());
                this.campoCedula.disable();
                comboCandidatos.setVisible(true);
            botonVotar.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(rootPane, "el votante no existe");
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "ya hay un voto registrado para esta eleccion");
        }
    }//GEN-LAST:event_botonVerificarActionPerformed

    private void botonVotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVotarActionPerformed
        int idEleccion = Integer.parseInt(labelId.getText());
        String idVotante = labelVotante.getText();
        String[] partesComboCandidato = this.comboCandidatos.getSelectedItem().toString().split("-", 2);
        String idCandidato = partesComboCandidato[1];
        ClsVoto voto = new ClsVoto(idEleccion, idVotante, idCandidato);
        ClsMensaje mensaje = this.controladorVoto.AgregarVoto(voto);

        if (mensaje.getTipo().equals(mensaje.OK)) {
            this.setVisible(false);
            menu.setVisible(true);

        }

        JOptionPane.showMessageDialog(rootPane, mensaje.getDescripcion());


    }//GEN-LAST:event_botonVotarActionPerformed
    public ClsVotante BuscarVotante(String id) {

        for (ClsVotante votante : this.Votantes) {

            if (votante.getNumeroDocumento().equals(id)) {
                return votante;
            }
        }
        return null;
    }

    public void ObtenerVotantes() {
        this.Votantes = this.controlador.ObtenerVotantes();
    }

    public void ObtenerCandidatos(String idEleccion) {
        LinkedList<ClsCandidato> candidatos = this.controladorEleccion.ObtenerCandidatosEleccion(idEleccion);
        DefaultComboBoxModel model = (DefaultComboBoxModel) this.comboCandidatos.getModel();
        model.removeAllElements();

        for (ClsCandidato candidato : candidatos) {
            model.addElement(candidato.getNombre() + "-" + candidato.getNumeroDocumento());
        }

        this.comboCandidatos.setModel(model);

    }
    public void ObtenerVotos() {
        this.Votos = this.controladorVoto.obtenerVotos();
    }
    public ClsVoto BuscarVoto(int idEl, String idVo) {
        
        for (ClsVoto voto : this.Votos) {
            
            if (voto.getIdEleccion()==idEl) {
                if (voto.getIdVotante().equals(idVo)) {
                return voto;
            }
            
        }
        }
        
        return null;
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameVotar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameVotar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameVotar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameVotar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameVotar(null, 0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonMenu;
    private javax.swing.JButton botonVerificar;
    private javax.swing.JButton botonVotar;
    private javax.swing.JTextField campoCedula;
    private javax.swing.JComboBox<String> comboCandidatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelCandidato;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelVotante;
    // End of variables declaration//GEN-END:variables

    public JLabel getlabelId() {
        return labelId;
    }

    public void setlabelId(JLabel labelId) {
        this.labelId = labelId;
    }

}
